config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'jobs' => 'static_pages#jobs'

  get 'privacy' => 'static_pages#privacy'



  get 'loaderio-0a7e4837e88f50cf53f7be88cd053c92' => 'static_pages#loaderio-0a7e4837e88f50cf53f7be88cd053c92.txt'


  match '/socials',     to: 'socials#new',             via: 'get'
  resources "socials", only: [:new, :create]

  get 'termsandconditions' => 'static_pages#termsandconditions'

  get 'contact_us', to: 'messages#new', as: 'new_message'
  post 'contact_us', to: 'messages#create', as: 'create_message'


  match '/lostproperty', to: 'lost_items#new', via: 'get' 
  resources 'lost_items', only: [:new, :create]
  
  resources :posts,  only: [:show, :index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tickets, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lost_item.rb
class LostItem < MailForm::Base
  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :date, :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS Lost Property Enquiry",
      :to => "lostproperty@rock-city.co.uk",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end

end

app/models/lostproperty.rb
class Lostproperty < MailForm::Base

  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS website enquiry",
      :to => "info@ipsofactouk.com",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body, :subject, :mobile
  validates :name, :email, :body, :subject, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostImageUploader
  default_scope { order("created_at DESC") }
end

app/models/social.rb
class Social < MailForm::Base
  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
 
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS social enquiry",
      :to => "info@carpenoctum.co.uk",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  mount_uploader :small_image, SmallImageUploader
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :square_image, SquareImageUploader

  default_scope { order(date: :asc) }

  scope :past, ->{ where("date < ?", Time.now)}
  scope :upcoming, -> { where("date >= ?", Time.now)}


end

app/controllers/lost_items_controller.rb
class LostItemsController < ApplicationController

  def new
    @lost_item = LostItem.new
  end

  def create
    @lost_item = LostItem.new(params[:lost_item])
    @lost_item.request = request
    if @lost_item.deliver
      redirect_to lostproperty_path, notice: "Thank you! Your message has been sent. Please note: It may take up to 48hrs for you to hear anything. If no reply, your item has sadly not been found."
    else
      flash.now[:error] = @lost_item.errors.full_messages
      render :new
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      redirect_to new_message_url, notice: "Your message has been sent. We will be in touch soon!"
    else
      flash[:notice] = "There was an error sending your message. Please try again."
      render :new
    end
  end

  private

    def message_params
      params.require(:message).permit(:name, :email, :body, :subject)
    end
      
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:image, :title, :description, :date, :author)
    end
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController

    def new
      @social = Social.new
    end

    def create
      @social = Social.new(params[:social])
      @social.request = request
      if @social.deliver
       
        redirect_to socials_path, notice: "Thank you! Your message has been sent."
      else
        flash.now[:error] = 'Cannot send message.'
        render :new
      end
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.upcoming

  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:small_image, :cover_image, :square_image, :ticket_link_id, :date, :opening_time, :theme, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lost_items_helper.rb
module LostItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRISIS</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="<%= image_url "favicon-32x32.png" %>" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ff0000">
    <meta name="theme-color" content="#ffffff">
    <!-- Start of carpenoctum Zendesk Widget script -->
    <script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(e){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var e=this.createElement("script");n&&(this.domain=n),e.id="js-iframe-async",e.src="https://assets.zendesk.com/embeddable_framework/main.js",this.t=+new Date,this.zendeskHost="carpenoctum.zendesk.com",this.zEQueue=a,this.body.appendChild(e)},o.write('<body onload="document._l();">'),o.close()}();
    /*]]>*/</script>
    <!-- End of carpenoctum Zendesk Widget script -->

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-WXWDNL');</script>
    <!-- End Google Tag Manager -->

    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '472065639617297'); // Insert your pixel ID here.
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=472065639617297&ev=PageView&noscript=1"
    /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WXWDNL"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= render "partials/nav" %>
    <%= yield %>
    <%= render "partials/footer" %>

  <script>
  window.counter = function() {
    // this refers to the html element with the data-scroll-showCallback tag
    var span = this.querySelector('span');
    var current = parseInt(span.textContent);

    span.textContent = current + 1;
  };

  document.addEventListener('DOMContentLoaded', function(){
    var trigger = new ScrollTrigger({
      addHeight: true
    });
  });
  </script>
  <!-- <script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '01666707-96cb-4f07-a3a0-ce1d95347781', f: true }); done = true; } }; })();</script> -->
  </body>
</html>

app/views/partials/_event-carousel.html.erb
<div data-scroll="toggle(.fromTopIn, .fromTopOut) once" id="homepage-event-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
  
  <div class="carousel-inner" role="listbox">
  <% @tickets.each_with_index do |ticket, index| %>
    <div class="carousel-item img-fluid <% if index == 0 %>active<% end %>">
      <%= image_tag ticket.cover_image_url(:thumb) if ticket.cover_image? %>
    </div>
<% end %>
    
  </div>
  <a class="left carousel-control" href="#homepage-event-carousel" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#homepage-event-carousel" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/partials/_footer.html.erb
<footer class="mt-3">
<div class="container py-2 sm-center">
  <div class="row">
    <div class="col-md-4 py-2">
      <%= image_tag("white_crisis_logo.svg", :alt => "CRISIS Logo", :class => "navbar-brand") %>
      <ul class="footer-list my-2">
      <li class="d-inline"><%= link_to 'Home', root_url %></li> |
      
      <li class="d-inline"><%= link_to 'About', about_url %></li> |
      
      <li class="d-inline"><%= link_to 'News', posts_url %></li> |
      
      <li class="d-inline"><%= link_to 'Tickets', tickets_url %></li> |
      <li class="d-inline"><%= link_to 'Contact', new_message_path %></li>
      </ul>

      <a class="white" href="http://www.carpenoctum.co.uk">Carpe Noctum Ltd</a> &copy; 2010

      <div class="mt-1"><small><%= link_to 'Terms', termsandconditions_path %> | <%= link_to 'privacy policy', privacy_path %></small></div>
    </div>
    
    <div class="col-md-4 py-2 sm-center">
    <div class="">
      <span class="fa-stack fa-lg">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i>
      </span>
      <p class="d-inline"><span>CRISIS, 8 Talbot Street</span> Nottingham</p>
    </div>
    <div>
      <span class="fa-stack fa-lg">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
      </span>
      
      <p class="d-inline">0330 332 0611</p>
    </div>
    <div>
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
    </span>
      
      <p class="d-inline"><a class="white" href="mailto:info@carpenoctum.co.uk">info@carpenoctum.co.uk</a></p>
    </div>
      
    </div>
    <div class="col-md-4 py-2 sm-center">
    
      <h6>About the company</h6>
    <p class="">
      CRISIS &#174; is a Carpe Noctum brand. Welcome to the UK's Biggest Weekly Student night in Nottingham.
    </p>
    <div class="">
      <a href="https://facebook.com/ilovecrisis">
      <span class="fa-stack fa-lg">
        <i class="fa fa-square fa-stack-2x"></i>
        <i class="fab fa-facebook-square fa-stack-1x fa-inverse"></i>
      </span></a>


      <a href="https:/twitter.com/ilove_crisis">
        <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-twitter-square fa-stack-1x fa-inverse"></i>
        </span></a>
      </a>

      <a href="https://plus.google.com/+crisisnottingham">
      <span class="fa-stack fa-lg">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fab fa-google-plus fa-stack-1x fa-inverse"></i>
      </span>
      </a>

      <a href="https://instagram.com/wearecrisis">
      <span class="fa-stack fa-lg">
          <i class="fa fa-square fa-stack-2x"></i>
          <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
      </span>

      </a>
      <a href="https://www.youtube.com/user/carp3n0ctum/videos">
        <span class="fa-stack fa-lg">
            <i class="fa fa-square fa-stack-2x"></i>
            <i class="fab fa-youtube-square fa-stack-1x fa-inverse"></i>
        </span>
      </a>

    </div>
      
    </div>
  </div>
  </div>
  </footer>

app/views/partials/_icons.html.erb
<div class="light-grey-band mt-5">
  <div class="container">
    <div class="row icon-band">
     <div data-scroll="toggle(.fromRightIn, .fromRightOut) once" class="col-md-3 text-block">
        <%= image_tag("photos-icon.svg", :alt => "Photos Icon", :class => "icons") %>
       <h4 class="">Photos</h4>
       <p>A taster of what its like on Wednesdays at CRISIS in Nottingham</p>
     </div>

     <div data-scroll="toggle(.fromRightIn, .fromRightOut) once" class="col-md-3 text-block">
        <%= image_tag("ticket-icon.svg", :alt => "Ticket Icon", :class => "icons") %>
       <h4 class=""><%= link_to 'Tickets', tickets_path %></h4>
       <p>Pick up tickets to Nottingham's favourite student night</p>
     </div>
     <div data-scroll="toggle(.fromRightIn, .fromRightOut) once" class="col-md-3 text-block">
        <%= image_tag("group-social.svg", :alt => "Social Icon", :class => "icons") %>
       <h4 class=""><%= link_to 'Socials', socials_path %></h4>
       <p>Are you part of a team, club or society organisation? We can help sort out your social to CRISIS.</p>
     </div>
     <div data-scroll="toggle(.fromRightIn, .fromRightOut) once" class="col-md-3 text-block">
        <%= image_tag("lost_prop_icon.svg", :alt => "Lost Property Icon", :class => "icons") %>
       <h4 class=""><%= link_to 'Lost Property', lostproperty_path %></h4>
       <p>Sad times. Hopefully we can help find your stuff.</p>
     </div>
    </div>    
  </div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to image_tag("white_crisis_logo.svg", :alt => "CRISIS Logo", :class => "navbar-brand hidden-md-down"), root_url %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>

      <li class="nav-item">
        <%= link_to 'News', posts_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      
      <li class="nav-item">
        <%= link_to 'Tickets', tickets_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      
      <li class="nav-item">
        <%= link_to 'Socials', socials_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Jobs', jobs_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Lost Property', lostproperty_url, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      <li class="nav-item">
        <a href="https://carpenoctum.zendesk.com/hc/en-us" class="nav-link hvr-underline-reveal">Help</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', new_message_path, :class =>'nav-link hvr-underline-reveal' %>
      </li>
      
    </ul>
    
  </div>
</nav>