config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'jobs' => 'static_pages#jobs'

  get 'privacy' => 'static_pages#privacy'



  get 'loaderio-0a7e4837e88f50cf53f7be88cd053c92' => 'static_pages#loaderio-0a7e4837e88f50cf53f7be88cd053c92.txt'


  match '/socials',     to: 'socials#new',             via: 'get'
  resources "socials", only: [:new, :create]

  get 'termsandconditions' => 'static_pages#termsandconditions'

  get 'contact_us', to: 'messages#new', as: 'new_message'
  post 'contact_us', to: 'messages#create', as: 'create_message'


  match '/lostproperty', to: 'lost_items#new', via: 'get' 
  resources 'lost_items', only: [:new, :create]
  
  resources :posts,  only: [:show, :index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tickets, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lost_item.rb
class LostItem < MailForm::Base
  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :date, :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS Lost Property Enquiry",
      :to => "lostproperty@rock-city.co.uk",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end

end

app/models/lostproperty.rb
class Lostproperty < MailForm::Base

  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS website enquiry",
      :to => "info@ipsofactouk.com",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body, :subject, :mobile
  validates :name, :email, :body, :subject, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostImageUploader
  default_scope { order("created_at DESC") }
end

app/models/social.rb
class Social < MailForm::Base
  attribute :name,      :validate => true
  attribute :mobile,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
 
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CRISIS social enquiry",
      :to => "info@carpenoctum.co.uk",
      :from => %("#{name}" <#{email}>),
      :reply_to => %<#{email}>
    }
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  mount_uploader :small_image, SmallImageUploader
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :square_image, SquareImageUploader

  default_scope { order(date: :asc) }

  scope :past, ->{ where("date < ?", Time.now)}
  scope :upcoming, -> { where("date >= ?", Time.now)}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lost_items_controller.rb
class LostItemsController < ApplicationController

  def new
    @lost_item = LostItem.new
  end

  def create
    @lost_item = LostItem.new(params[:lost_item])
    @lost_item.request = request
    if @lost_item.deliver
      redirect_to lostproperty_path, notice: "Thank you! Your message has been sent. Please note: It may take up to 48hrs for you to hear anything. If no reply, your item has sadly not been found."
    else
      flash.now[:error] = @lost_item.errors.full_messages
      render :new
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      redirect_to new_message_url, notice: "Your message has been sent. We will be in touch soon!"
    else
      flash[:notice] = "There was an error sending your message. Please try again."
      render :new
    end
  end

  private

    def message_params
      params.require(:message).permit(:name, :email, :body, :subject)
    end
      
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:image, :title, :description, :date, :author)
    end
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController

    def new
      @social = Social.new
    end

    def create
      @social = Social.new(params[:social])
      @social.request = request
      if @social.deliver
       
        redirect_to socials_path, notice: "Thank you! Your message has been sent."
      else
        flash.now[:error] = 'Cannot send message.'
        render :new
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  def sevenlegged
  end
  def home
   @tickets = Ticket.upcoming
   
  end

  def jobs
  end

  def loaderio
  end


  def termsandconditions
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.upcoming

  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:small_image, :cover_image, :square_image, :ticket_link_id, :date, :opening_time, :theme, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lost_items_helper.rb
module LostItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
 
  <%= image_tag(@post.image_url) if @post.image.present? %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>


<%= link_to 'Back', posts_path %>

app/views/static_pages/termsandconditions.html.erb
<div class="container my-5">
<h1>Terms and Conditions</h1>

<p>By purchasing a Ticket for a CRISIS or entering via our guestlist or paying admission on the door you are agreeing to the following terms and conditions and our <%= link_to 'privacy policy', privacy_path %>.</p>

<p>Use of this website is also subject our <%= link_to 'privacy policy', privacy_path %>.</p>

<p>Last updated 24/10/17</p>

<h5>Definitions</h5>

  <ul>
    <li>'Customer' means an individual or individuals who purchase Tickets for an 'Event' on the CRISIS website through our third party 'Ticketing provider', purchases a paper Ticket through an 'Event organiser' representative, or pays their admission at the club on arrival.</li>

    <li>A 'Ticket' is either a piece of paper or electronic equivalent that gives the holder a right to enter the 'Event' subject to the terms of the 'Venue' and 'Event Organisers'. The electonic equivalent must have a barcode of sufficient quality to be considered valid.</li>

    <li>A 'Ticket Expiry Time' is a period of time for which the Ticket is valid. This usually takes the form of being valid before a specified time or may be valid only after a certain time.</li>

    <li>'Ticketing Provider' is the company that provide our electronic Ticketing service. This is currently "Fixr" who are owned and operated VIPR Digital Limited. VIPR Digital Limited is a private limited company, registered in England (company number: 8184813, registered office: Fourth Floor, 9 Holyrood Street, London SE1 2EL). Our VAT registration number is 161892490.</li>

    <li>The "Venue" is Rock-City Nightclub, 8 Talbot Street, Nottingham, NG1 5GG. Rock-City is owned and operated by DHP Family Ltd. DHP Family Ltd are is a private limited company registered in England and Wales with company registration number 00259388. Their registered office is 2, Lace Market Square, Nottingham, NG1 1PB</li>

    <li>"CRISIS" is a nightclub brand owned by Carpe Noctum Ltd. Carpe Noctum Limited are a company registered in England and Wales. Company registration number: 06020429. Registered office: 3, The Banks, Bingham, NG13 8BL.VAT Registration: 984 7837 49. The office address is Unit T11, Lenton Business Centre, Nottingham, NG7 2BY</li>

    <li>"Event Organisers" or "Carpe Noctum" are the Organisers of the Event and promoters.</li>

    <li>'The University of Nottingham' is a public research university based in Nottingham, Nottinghamshire, England, United Kingdom.</li>

    <li>'Student at another University' is a student studying at a University other than 'The University of Nottingham'.</li>

    <li>'Non-student' is a member of the public who is not currently studying at a University institution.</li>

    <li>The "Event" is a club night branded "CRISIS". It is usually held on Wednesday nights during 'The University of Nottingham's' academic term time.</li>

    <li>A "Sports Cardholder" has an ID card that is the equivalent of a 'Ticket'. Customers who are a "Sports Cardholder" are subject to the same terms and conditions as a 'customer' purchasing a 'ticket' plus any additional terms printed on the reverse of the card.</li>


  </ul>

<h5>TICKETS</h5>
  <ul>
    <li>The purchase of a 'Ticket' in either electronic, paper or paying on the door format consititutes acceptance of the Terms and Conditions here.</li>
    <li>The purchase of a 'Ticket' means you agree to the <a href="http://www.rock-city.co.uk/venue-info-hire/26-customer-policy">'Venue' terms and conditions</a>.</li>
    <li>The purchase of a 'Ticket' means you agree to the <a href="https://fixr-app.com/customer-terms-and-conditions">'Ticketing provider's' terms and conditions</a>.</li>
    <li>A 'Ticket' may have restrictions on the time it is valid known as 'Ticket Expiry Time'. Failure to arrive by the time stipulated constitutes a breach of the 'Event Organisers' Terms, which shall entitle the 'Event Organiser' to refuse you entry. No refunds are issued in such circumstances.</li>
    <li>A 'Ticket' must not be resold by means other than through the 'Ticketing provider' application - "Fixr" or their website. The 'Venue' and 'Event Organisers' reserve the right to refuse Tickets that have been resold by any other means. This includes but is in no way limited to screenshots. No refunds will be issued to tickets resold outside the 'Ticketing povider</li>
    <li>Reselling a ticket by more than 20% of it's original face value is strictly prohibited. Those persons reported to us will have their tickets cancelled.</li>
    <li>A 'Ticket' in electronic format either displayed on a phone screen or printed out must have a barcode of sufficient quality to be scanned. Failure to provide a quality barcode may result in your admission being refused. We strongly recommend using the 'Ticketing provider' app or pdf versions of Tickets. Screenshots are not permitted. Photos of screens are not permitted</li>
    <li>Ticket transfers cannot be done after 9pm</li>
    <li>Ticket transfers are limited to a maximum of three times. You will be unable to transfer a ticket beyond this limit. Do not attempt to do so.</li>
    <li>The 'Event Organisers' reserve the right to reasonably alter any previously stated 'Ticket Expiry Times' subject to providing at least 4 hours notice by email.</li>
    <li> Entrance to the 'Event' will only be authorised upon presentation of a valid 'Ticket' or paid door admission. Removing any part of, altering or defacing the 'Ticket' may invalidate your 'Ticket'.</li>
    

  </ul>

<h5>ADMISSIONS POLICY</h5> 

  <ul>
    <li>Admission to the 'Event' is strictly for over 18s only. ID will be required to prove you are over 18 years old. Failure to provide ID may result in a refusal of your admission. No refunds will be issued in such circumstances.</li>

    <li>The 'Event' is primarily a student night for students studying full or part time at 'The University of Nottingham'. You may be asked to provide student ID to prove you are a student at that institution. Failure to provide student ID may result in a refusal of your admission. No refunds will be issued in such circumstances.</li>

    <li>'Students at another University' such as Nottingham Trent University or any other University are welcome to attend the 'event' but must be aware that they are permitted only at the discretion of the 'Venue' and 'Event Organisers'. It is recommended you stick to smaller mixed gender groups. If you have purchased a 'ticket' and are refused entry for being a 'Student at another University' then you may contact us for a refund.</li>

    <li>We allow 'non-student' guests at the descretion of the 'Event Organisers'. This is usually done at a ratio of one student to one non-student, but this is entirely discretionary and the 'Event Organisers' reserve the right to refuse admission to any non-student. No refunds will be issued such circumstances.</li>

    <li>The 'Venue' and 'Event Organisers' reserve the right to refuse admission to any 'customer' that appears too drunk or they believe may be under the unfluence of illegal drugs. No refunds will be issued such circumstances.</li>

    <li>In rare circumstances we may ask you to wait for your admission into the Venue even with a valid Ticket to ensure the 'Venue's' capacity regulations are adhered to. 'Customers' who have a 'Ticket' that subsequently exceeds its 'Ticket Expiry Time' will still be admitted to the Venue when space is available. Those 'customers' waiting longer than 1 hour  or who are refused entry due to insufficient capacity will be entitled to a refund.</li>

    <li>You may be subject to a search prior to entry to the 'Venue'. Entry will not be permitted to any person who is carrying in his or her possession prohibited items, which shall include but not be limited to, food, drink, chemicals of any kind, bottles, cans, laser pens or weapons of any kind.  Such prohibited items shall be confiscated by the 'Venue' and kept by the 'Venue' during the 'Event' for return to the person after the 'Event'.  The 'Venue' shall not be responsible for any loss of or damage to such prohibited items during the 'Event'.</li>

    <li>The 'Venue' may eject any person who fails to comply with their Terms and Conditions or who in the opinion of The 'Venue' or 'Event organiser' represents a security risk, nuisance or annoyance to the staging of the Event. No refunds will be issued in such circumstances</li>

    <li>The 'Venue' or 'Event Organisers' may refuse admission to the 'Venue ' to any person in its absolute discretion, including for health and safety, licensing reasons or where a Ticket is void.</li>
  </ul>

  <h5>CANCELATIONS AND POSTPONEMENT</h5>
  <ul>
    <li>If the 'Event' is cancelled or postponed prior to the start of the Event, You shall be entitled to a refund in the sum of the face value of the Ticket. The booking fee is non-refundable.</li>

    <li> If the 'Event' is postponed, the Ticket will be valid for the rearranged date. It is the 'Customer's' responsibility to check the date and time of the rearranged Event.</li>

    <li>All advertised 'Events' may be subject to change where reasonably necessary, without prior warning. If there is a material change to the programme of the Event (which in the reasonable opinion of the 'Event Organisers' makes the 'Event' materially different to what You could reasonably expect), then You may be entitled to claim a refund from the 'Event Organisers'  Refunds are not available for changes to supporting acts for an Event.</li>

    <li>These Terms and Conditions do not affect your statutory cancellation rights as a consumer. For further information about your statutory rights contact Citizens Advice, Consumer Direct or the Department for Business, Innovation and Skills.</li>
  </ul>

  <h5>GENERAL</h5>
  <ul>
    <li>If the 'Event Organisers' or the 'Venue' fail to enforce any of its rights and obligations under these Terms and Conditions it shall not mean that it has waived its rights to do so.</li>

    <li>Each of the parties agree that it has not entered not entered into these Terms and Conditions in reliance on, and shall have no remedy in respect of, any statement, representation, covenant, warranty, undertaking or indemnity by any person other than as expressly set out in these Terms and Conditions.</li>

    <li>The 'Event Organisers' make use of photographers and videographers to document the night and use in publicity materials. Upon entering the 'venue' your consent to be photographed and videoed is assumed. If you do not wish to be filmed or photographed please tell the member of staff with the camera to refrain and they will comply. If there is footage/photographs published of you online in the background, by mistake, or if you have changed your mind about consent please email info@carpenoctum.co.uk for their removal.</li>

    <li> These Terms and Conditions are governed by English law and the parties submit to the exclusive jurisdiction of the English courts.</li>

    <li>The 'Event Organisers' will not be liable for any loss, injury or damage to any person or property howsoever caused, other than caused as a result of negligence of the 'Event organiser'. Nothing in these Terms and Conditions seeks to exclude or limit the 'Event Organisers' or the liability for death or personal injury caused by its negligence, fraud or other type of liability which cannot by law be excluded or limited. </li>

    <li>The 'Event' will generally finish at 3am. In some circumstances we may operate for longer as advertised on the Event. The 'Venue' and 'Event Organisers' reserve the right to close certain rooms within the 'Venue' in order to maintain atmosphere and enjoyment for the 'customers'.</li>

    <li>The 'Venue' and 'Event Organisers' reserve the right to close the 'Event' earlier than the stated finish time where overall 'customers' in the building is less than 300 persons. No refunds are available under such circumstances</li>

  </ul>

 
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div data-scroll="toggle(.fromTopIn, .fromTopOut) once" class="cover-img">
  <div class="container hero-content">
    <div class="row align-items-center">
    <div class="col-4 col-md-3">
    <img class="img-fluid" src="<%=@ticket.square_image %>">
    </div>
    <div class="col-8 col-md-9">

    <h2 class="white show-title"><%= @ticket.theme %> | <span class="red"><%= @ticket.date.to_formatted_s(:rfc822) %></span></h2>
    <p class="text-uppercase release-info mb-0">Tickets released: <span class="px-1 red-background"><%= @ticket.ticket_release_date.to_formatted_s(:rfc822) %></span> <small>at</small> <span class="px-1 white-background red bold"><%= @ticket.ticket_release_time.strftime("%H:%M") %></span></p>
    </div>

    </div>
  </div>
</div>
<div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="container">


<div class="container">
  <h3 data-scroll="toggle(.fromTopIn, .fromTopOut) once" class="mt-3">Ever wondered about our tickets...</h3>
   
      <div id="accordion" role="tablist" aria-multiselectable="true">
        <div class="card">
          <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card-header" role="tab" id="headingOne">
            <h5 class="mb-0">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            How are we allocating tickets in 2018?
            </a>
            </h5>
          </div>

          <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="card-block">
                Except for All Nighters, we allocate 2100 tickets for advance purchase. They are as follows:
                <ul class="pt-2">
                    <li>500 Sports Teams Tickets</li>
                    <li>150 Socials Non-Sport (Socs / JCRS) </li>
                    <li>1150 General Online Sales</li>
                    <li>300 Second Release tickets (Thursdays at 4pm)</li>
                   
                </ul>
                <p>
                We then allow approximately 200-400 door admissions depending on how many of the tickets show up. As people leave, we admit any spare capacity there too.
                </p>
                <p>For All Nighters, it's a free-for-all with everything going online.</p>
            </div>
          </div>
        </div>
      <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card">
        <div class="card-header" role="tab" id="SecondRelease">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSecondRelease" aria-expanded="false" aria-controls="collapseSecondRelease">
              What are second release tickets?
            </a>
          </h5>
        </div>
        <div id="collapseSecondRelease" class="collapse" role="tabpanel" aria-labelledby="SecondRelease">
          <div class="card-block">
            <p>Second release tickets are a new allocation of 300 tickets saved for putting on sale the week before the corresponding CRISIS event. We have added these as part of efforts to reduce the markups in the reselling secondary ticket market. Our hope is to add more tickets in the run up, flood the market a bit and keep the resell price down</p>
            <p><strong>Second Release tickets go on sale Thurdsays at 4pm </strong></p>
            <p>Please report any resold tickets that are more than 20% of the original price. We will cancel those tickets and any other that person holds.</p>
          </div>
        </div>
      </div>
      <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card">
        <div class="card-header" role="tab" id="headingTwo">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Why are sports tickets £100?
            </a>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="card-block">
            Just a quirk of the ticketing system. You could technically buy a £100 ticket if you really wanted to go and were slightly nuts, but what we do is issue a discount code to the Sports teams that have booked a social with us for that week. They then enter this code on this section of tickets and it brings the ticket down to the correct price.
          </div>
        </div>
      </div>
      <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card">
        <div class="card-header" role="tab" id="headingThree">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Why are ticket times early?
            </a>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="card-block">
            <p>Demand for tickets is usually around 4 times what we have in available space. So, in order to try and get as many tickets out to those what want them we use time to stagger them.</p>
            <p>So, just like a restaurant taking a booking at 7pm and again for the same table for 9pm, we utilise time slots to recycle space. It also allows us to make the ticket queue nice and speedy as people arrive in waves.</p>
            <p>Of course, the downside is we have to be strict on the ticket times.</p>
            <p>You may also notice the ticket expiry times can vary by over an hour on some weeks. This is usually due to a music gig occuring on the same night in Rock City's main hall. For these events, we allow paying customers to enter BCL at the start, then as the gig is cleared, the doors open to the main room. At the same time, ticketholders can then also get access through the main entrance.</p>
          </div>
        </div>
      </div>

      <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card mb-3">
        <div class="card-header" role="tab" id="headingFour">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Why, after selecting the number of tickets, did I not then get them?
            </a>
          </h5>
        </div>
        <div id="collapseFour" class="collapse" role="tabpanel" aria-labelledby="headingFour">
          <div class="card-block">
            <p>This is the way the ticketing provider issue tickets. When you select tickets, it is not a basket like other sites. It something we have raised with them and they are changing it in the next release (approx October).</p>
            <p>The advantage of their way is if you are pre-registered or have bought before, the transaction is rapid, but if you haven't registered or bought before you may lose whats in your basket to people who have.</p>
          </div>
        </div>
      </div>

      <div data-scroll="toggle(.fromBottomIn, .fromBottomOut) once" class="card mb-3">
        <div class="card-header" role="tab" id="headingFive">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
              Do we allow ticket reselling?
            </a>
          </h5>
        </div>
        <div id="collapseFive" class="collapse" role="tabpanel" aria-labelledby="headingFive">
          <div class="card-block">
            <p>Yes, you can resell tickets within the FIXR ticketing app or website up till 9pm on the day. There is a transfer limit of 3 times. After which, you will be unable to transfer tickets.</p>
            <p><strong class="red">Please note: This is the only reselling we accept.</strong> Tickets resold another way, e.g. screenshot on "buy and sell" are prohibited.</p>
            <p>We are strongly against the marking up of tickets for profit. This is why we only allow transactions of up to 4 tickets per transaction on regular tickets and 1 per person on Sports Tickets.</p>
            <p>If you wish to report someone marking up tickets excessively please <a href="mailto:info@carpenoctum.co.uk">email us</a></p>
          </div>
        </div>
      </div>
  

  </div>

</div>



<iframe src="https://fixr.co/event/<%= @ticket.fixr %>?compact=true"
        class="fixr">
</iframe>
<div><small>All ticket purchases are subject to our <%= link_to 'Terms and Conditions', termsandconditions_path %> and <%= link_to 'privacy policy', privacy_path %></small></div>
<%= link_to 'Back', tickets_path %>
</div>